---
title: &siteTitle Bunker project
timezone: Europe/Kiev
url: https://bunker.org.ua
baseurl: ''
lang: en
direction: ltr

defaults:
  - scope: { path: '' }
    values:
      lang: en
      layout: default
  - scope: { path: uk }
    values: { lang: uk }
  - scope: { path: ru }
    values: { lang: ru }

exclude: [Makefile]

i18n_title:
  en: *siteTitle
  uk: Проект «Бункер»
  ru: Проект «Бункер»

i18n_lang_names:
  en: English
  uk: Українська
  ru: Русский

i18n_footer:
  en: © Dmytro K.
  uk: © Дмитро К.
  ru: © Дмитрий К.
