---
title: &siteTitleEn The Bunker project
description: &siteDescEn Private service for web hosting, DNS, and email

timezone: Europe/Kyiv
url: https://bunker.org.ua
baseurl: ''
lang: en

defaults:
  - scope:
      path: ''
    values:
      lang: en
      layout: default
  - scope:
      type: posts
    values:
      layout: post

exclude:
  - Makefile
  - README.md
  - bunker.org.ua.tar.gz

sass:
  style: compact

i18n_lang_order:
  - uk
  - en

i18n:
  feed_title:
    en: *siteTitleEn
    uk: Проект «Бункер»
    ru: Проект «Бункер»
  description:
    en: *siteDescEn
    uk: Приватний сервіс для веб-хостингу, DNS та електронної пошти
    ru: Частный сервис для веб-хостинга, DNS и электронной почты
  homepage:
    en: Homepage
    uk: Головна сторінка
    ru: Главная страница
  lang_name:
    en: English
    uk: Українська
    ru: Русский
  other_lang:
    en: 'Other languages:'
    uk: 'Інші мови:'
    ru: 'Другие языки:'
  footer:
    en: © D.K.
    uk: © Д.К.
    ru: © Д.К.
  feed_author:
    en: Dmytro Kolesnykov
    uk: Дмитро Колесников
    ru: Дмитрий Колесников
