---
title: &siteTitleEn The Bunker project
description: &siteDescEn Private service for web hosting, DNS, and email

timezone: Europe/Kyiv
url: https://bunker.org.ua
baseurl: ''
lang: en

defaults:
  - scope:
      path: ''
    values:
      lang: en
      layout: default
  - scope:
      type: posts
    values:
      layout: post

exclude:
  - Makefile
  - README.md
  - bunker.org.ua.tar.gz

sass:
  style: compact

i18n_lang_order:
  - uk
  - en
  - pl
  - de

i18n:
  title:
    en: *siteTitleEn
    uk: Проект «Бункер»
    pl: Projekt „Bunkier”
    de: Das Projekt „Bunker“
  description:
    en: *siteDescEn
    uk: Приватний сервіс для веб-хостингу, DNS та електронної пошти
    pl: Prywatny serwis dla hostingu internetowego, DNS i e-poczty
    de: Privater Dienst für Webhosting, DNS und E-Mail
  homepage:
    en: Homepage
    uk: Головна сторінка
    pl: Strona główna
    de: Startseite
  lang_name:
    en: English
    uk: Українська
    pl: Polski
    de: Deutsch
  other_lang:
    en: 'Other languages:'
    uk: 'Інші мови:'
    pl: 'Inne języki:'
    de: 'Andere Sprachen:'
  footer:
    en: © D.K.
    uk: © Д.К.
    pl: © D.K.
    de: © D.K.
  feed_author:
    en: Dmytro Kolesnykov
    uk: Дмитро Колесников
    pl: Dmytro Kolesnykov
    de: Dmytro Kolesnykov
